name: lint
on: [push, pull_request]
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run
